import Link from "next/link";
import { Star } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0F] text-slate-100">
      {/* Navbar */}
      <header className="sticky top-0 z-10 bg-[#0A0A0F]/80 backdrop-blur border-b border-[#2A2A3E] px-6 py-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 bg-indigo-600 rounded-lg flex items-center justify-center">
              <Star className="w-3.5 h-3.5 text-white" fill="currentColor" />
            </div>
            <span className="font-semibold text-white text-sm">AI Review Responder</span>
          </Link>
          <Link href="/register" className="text-sm bg-indigo-600 hover:bg-indigo-500 text-white font-semibold px-4 py-2 rounded-lg transition-all">
            Start free trial
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16 space-y-10">
        <div>
          <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-sm text-slate-500">Last updated: March 2026</p>
        </div>

        <div className="space-y-8 text-sm text-slate-400 leading-relaxed">

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-white">1. Service Description</h2>
            <p>
              AI Review Responder (operated by <strong className="text-white">Nostra</strong>) is a SaaS platform
              that helps businesses automatically generate and publish responses to Google Business reviews
              using artificial intelligence. By registering, you agree to these Terms of Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-white">2. Free Trial</h2>
            <p>
              New accounts receive a <strong className="text-white">14-day free trial</strong> with access to all
              features. No credit card is required to start. After the trial period ends, a paid subscription
              is required to continue using the service. Trial accounts that are not converted to a paid plan
              will be automatically restricted (read-only access) but data will not be deleted immediately.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-white">3. Subscriptions & Billing</h2>
            <ul className="list-disc list-inside space-y-1.5">
              <li>Subscriptions are billed monthly in advance</li>
              <li>Prices are listed in EUR and may be subject to VAT for EU customers</li>
              <li>Payments are processed by Stripe — we do not store credit card information</li>
              <li>Plan upgrades take effect immediately; downgrades take effect at the next billing cycle</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-white">4. Cancellation Policy</h2>
            <p>
              You may cancel your subscription at any time from the Billing section of your dashboard.
              Upon cancellation, your subscription remains active until the end of the current billing period.
              <strong className="text-white"> No refunds are issued for the current billing period.</strong>{" "}
              After cancellation, your account data is retained for 30 days before permanent deletion.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-white">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-1.5">
              <li>Use the service to generate spam, misleading, or defamatory content</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the API</li>
              <li>Share account credentials with multiple users (each user must have their own account)</li>
              <li>Use the service in violation of Google&apos;s Terms of Service</li>
            </ul>
            <p>
              We reserve the right to suspend or terminate accounts that violate these terms without notice.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-white">6. AI-Generated Content</h2>
            <p>
              Responses generated by AI are suggestions only. You are responsible for reviewing any
              content before publishing it to your Google Business Profile. We do not guarantee the
              accuracy, appropriateness, or effectiveness of AI-generated responses.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-white">7. Service Availability</h2>
            <p>
              We strive for 99% uptime but do not guarantee uninterrupted service. We are not liable
              for losses resulting from service downtime, including inability to respond to reviews.
              Planned maintenance will be communicated in advance when possible.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-white">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, Nostra shall not be liable for any
              indirect, incidental, special, or consequential damages arising from your use of the service,
              including loss of revenue, loss of data, or damage to reputation. Our total liability for
              any claim shall not exceed the amount paid by you in the three months preceding the claim.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-white">9. Intellectual Property</h2>
            <p>
              The AI Review Responder platform, its design, and code are the intellectual property of Nostra.
              Review content fetched from Google belongs to the respective authors. You retain ownership of
              any custom instructions and templates you create within the platform.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-white">10. Modifications to Terms</h2>
            <p>
              We may update these Terms of Service at any time. Significant changes will be communicated
              by email at least 14 days before they take effect. Continued use of the service after changes
              constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-white">11. Governing Law</h2>
            <p>
              These Terms are governed by the laws of <strong className="text-white">France</strong>.
              Any disputes shall be subject to the exclusive jurisdiction of the courts of France.
              For consumer disputes, you may also use the EU online dispute resolution platform at{" "}
              <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener noreferrer" className="text-indigo-400 hover:underline">
                ec.europa.eu/consumers/odr
              </a>.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-white">12. Contact</h2>
            <p>
              For questions about these Terms, contact us at{" "}
              <a href="mailto:contact@yourdomain.com" className="text-indigo-400 hover:underline">
                contact@yourdomain.com
              </a>.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-[#2A2A3E] py-8 px-6">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3 text-sm text-slate-600">
          <span>© 2026 Nostra — AI Review Responder</span>
          <div className="flex gap-5">
            <Link href="/" className="hover:text-slate-400 transition-colors">Home</Link>
            <Link href="/privacy" className="hover:text-slate-400 transition-colors">Privacy</Link>
            <Link href="/pricing" className="hover:text-slate-400 transition-colors">Pricing</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
